### ISSUE TITLE
GTC 2017 Task List

### ISSUE THREAD

**Issue by turambar** [SkymindIO/MultitaskPhysionetLab#1]
- [x] ~~Decide: for interface, should we use remote Desktop, SSH, or Jupyter~~
- [x] ~~Decide: _should we write a full DataVec pipeline for native Physionet, or should we just preprocess the data ahead of time and provide that (doable since we'll be using Docker files)?_~~ **Decision: no for GTC**
- [x] ~~Build out python data preparation pipeline~~
- [x] ~~Preprocess data and save back to disk as flattened time series~~
  - [x] ~~Make resampled version?~~
  - [x] ~~Make featurized version (I've gotten better results on featurized version in past)?~~
- [x] ~~Build Keras-based modeling pipeline~~
- [x] ~~Do some exploratory modeling in Keras to ballpark some results~~
- [x] ~~Write "simple" DataVec pipeline for preprocessed version of data~~
- [x] ~~Build DL4J modeling pipeline~~
- [x] ~~Set up Docker image~~
- [x] ~~Create slides and didactic material~~
