### ISSUE TITLE
Cloudera Blog Post Task List

### ISSUE THREAD

**Issue by turambar** [SkymindIO/MultitaskPhysionetLab#3]
- [ ] run experiments to test no. of workers vs. performance
- [ ] (maybe) see how performance is impacted when time columns are removed
- [ ] (maybe) run on a resampled version of data with hourly time steps
- [ ] (maybe) try target replication, a la _[Learning to Diagnose](https://arxiv.org/abs/1511.03677)_
  - [ ] @turambar: make resampled data
- [ ] (maybe) try multitask LSTM, a la _[Multitask Clinical Time Series](https://arxiv.org/abs/1703.07771)_
- [ ] build out a proper DataVec pipeline for raw data
